version: "3.9"
services:
  php:
    build: './build/php'
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
  mysql:
    build: './build/mysql'
    ports:
      - "9306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - dbData:/var/lib/mysql
      - ./build/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
volumes:
  app:
  dbData: